/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author PANJAITAN
 */
public class DaftarMinuman extends javax.swing.JFrame {

    public ArrayList nama = new ArrayList();
    private String idCount = "";
    
    private void TampilkanData(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No. ");
        model.addColumn("Nama");
        model.addColumn("Harga (Rp)");
        model.addColumn("");
        
        try{
            int no = 1;

            java.sql.ResultSet res = MySQL.GetData("SELECT * FROM minuman");
            
            while(res.next()){
                model.addRow(new Object[]{no++, res.getString(2), res.getString(3), res.getString(1)});
            }
            tabelMinuman.setModel(model);
            tabelMinuman.getColumnModel().getColumn(3).setMaxWidth(0);       
            tabelMinuman.getColumnModel().getColumn(3).setMinWidth(0);
        }catch(SQLException e){
            System.out.println("Errot : " + e.getMessage());
        }
    }
    
    private boolean cekKosong(boolean minuman){
        boolean hasil = true;
        if(txtTambahNamaMinuman.getText().isEmpty() || txtTambahHargaMinuman.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Nama atau Harga Minuman Harus Diisi!");
            hasil=true;
        }
        return false;
    }
    
    private boolean cekDataTable(String data){
        boolean hasil = nama.contains(data);
        return hasil;
    }
    
    private void Tambah(){
        if(cekKosong(true) == false){
            String namaItem = txtTambahNamaMinuman.getText();
            
            if(cekDataTable(namaItem) == false){
                nama.add(namaItem);
                try{
                String sql = "INSERT INTO minuman (nama,harga) VALUES ('"+txtTambahNamaMinuman.getText()+"','"+txtTambahHargaMinuman.getText()+"')";
                java.sql.Connection conn = (Connection)Konfig.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                TampilkanData();
                Hapus();
                }catch(HeadlessException | SQLException e){
                     JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }else{
                try{
                    String sql = "UPDATE minuman SET harga='"+txtTambahHargaMinuman.getText()+"' WHERE id='"+idCount+"'";
                    java.sql.Connection conn = (Connection)Konfig.configDB();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Update data berhasil ");
                    TampilkanData();
                }catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }
    
    private void Hapus(){
        txtTambahNamaMinuman.setText(null);
        txtTambahHargaMinuman.setText(null);
    }
    
    public void Tema(){
        try{
            UIManager.setLookAndFeel(new AluminiumLookAndFeel());
        }catch(UnsupportedLookAndFeelException ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * Creates new form DaftarMinuman
     */
    public DaftarMinuman() {
        initComponents();
        ImageIcon imageicon = new ImageIcon("src/Image/logo.png");
        setIconImage(imageicon.getImage());
        TampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMinuman = new javax.swing.JTable();
        btnHapusMinuman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTambahNamaMinuman = new javax.swing.JTextField();
        txtTambahHargaMinuman = new javax.swing.JTextField();
        btnSimpanMinuman = new javax.swing.JButton();
        btnBatalMinuman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Daftar Minuman");

        tabelMinuman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMinumanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMinuman);

        btnHapusMinuman.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapusMinuman.setText("Hapus");
        btnHapusMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMinumanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tambahkan Menu Minuman");

        jLabel3.setText("Nama Minuman");

        jLabel4.setText("Harga Minuman");

        txtTambahHargaMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTambahHargaMinumanActionPerformed(evt);
            }
        });

        btnSimpanMinuman.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimpanMinuman.setText("Simpan");
        btnSimpanMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanMinumanActionPerformed(evt);
            }
        });

        btnBatalMinuman.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBatalMinuman.setText("Batal / Clear");
        btnBatalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalMinumanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(txtTambahNamaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(txtTambahHargaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpanMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(btnHapusMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(168, 168, 168))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapusMinuman)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTambahNamaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTambahHargaMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanMinuman)
                    .addComponent(btnBatalMinuman))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalMinumanActionPerformed
        // TODO add your handling code here:
        Hapus();
    }//GEN-LAST:event_btnBatalMinumanActionPerformed

    private void btnSimpanMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanMinumanActionPerformed
        // TODO add your handling code here:
       Tambah();
    }//GEN-LAST:event_btnSimpanMinumanActionPerformed

    private void btnHapusMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMinumanActionPerformed
        // TODO add your handling code here:
        int baris = tabelMinuman.getSelectedRow();
        String id = tabelMinuman.getValueAt(baris, 3).toString();
        try{
            String sql = "DELETE FROM minuman WHERE id='"+id+"'";
            System.out.println(sql);
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();     
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        TampilkanData();
    }//GEN-LAST:event_btnHapusMinumanActionPerformed

    private void tabelMinumanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMinumanMouseClicked
        // TODO add your handling code here:
        int baris = tabelMinuman.rowAtPoint(evt.getPoint());
        String nama2 = tabelMinuman.getValueAt(baris, 1).toString();
        txtTambahNamaMinuman.setText(nama2);
        String harga2 = tabelMinuman.getValueAt(baris, 2).toString();
        txtTambahHargaMinuman.setText(harga2);
        
        idCount = tabelMinuman.getValueAt(baris, 3).toString();
    }//GEN-LAST:event_tabelMinumanMouseClicked

    private void txtTambahHargaMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTambahHargaMinumanActionPerformed
        // TODO add your handling code here:
        Tambah();
    }//GEN-LAST:event_txtTambahHargaMinumanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        Login frame = new Login();
        frame.Tema();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalMinuman;
    private javax.swing.JButton btnHapusMinuman;
    private javax.swing.JButton btnSimpanMinuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMinuman;
    private javax.swing.JTextField txtTambahHargaMinuman;
    private javax.swing.JTextField txtTambahNamaMinuman;
    // End of variables declaration//GEN-END:variables
}
